<template>
  <b-row align-h="center" align-v="center">
    <b-col sm="10" md="8">
      <b-card class="p-2 p-md-4 text-justify">
        <h3 class="py-3"> Lumenshine Terms of service </h3>
        <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nulla urna, euismod ac lacus quis, finibus tempus odio. Vivamus fermentum sed arcu ac tincidunt. Etiam interdum ornare sapien ut sollicitudin. Cras ultricies arcu nec tempus viverra. Nam molestie erat est, at fermentum ex tempor sit amet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In hac habitasse platea dictumst. </p>
        <p> Fusce suscipit eget nibh sed pharetra. Praesent in aliquet leo, in pharetra lacus. Suspendisse interdum volutpat lacus, eu imperdiet arcu consequat blandit. Vivamus interdum vulputate elit, sit amet rhoncus lorem iaculis rhoncus. Curabitur diam nibh, volutpat ut fringilla sit amet, sollicitudin at arcu. Quisque elementum est vitae arcu blandit eleifend. Duis luctus, augue ut convallis consequat, turpis lorem ullamcorper elit, at pellentesque neque lorem at nisi. Cras et mauris pellentesque, dictum metus quis, blandit nisl. Donec tempor maximus felis, vel pellentesque tellus luctus quis. Cras gravida eros a eros laoreet sollicitudin et ut nisi. Sed lacus ipsum, tempus vitae commodo non, interdum ut lorem. Praesent bibendum convallis feugiat. Proin ac est eleifend, iaculis urna at, auctor massa. Nullam ac facilisis est. </p>
        <p> Ut maximus felis et sodales ultricies. Praesent at mauris pellentesque diam pulvinar mattis. In sed orci risus. Etiam finibus dui vitae diam mattis, quis consectetur lorem consectetur. Curabitur eget velit nec justo varius efficitur. Curabitur eget eros fermentum purus placerat aliquam nec et nibh. Mauris pharetra laoreet interdum. Integer blandit iaculis posuere. Integer lacinia dignissim ipsum non tincidunt. Suspendisse volutpat sem ligula, et posuere turpis luctus non. Aliquam erat volutpat. Proin a magna et nunc varius viverra. Sed a dolor ullamcorper, tempus erat eget, porta mauris. Proin venenatis, sapien aliquam feugiat dictum, neque turpis pharetra diam, non sodales turpis ipsum nec purus. Nullam congue tempor eros, quis consectetur erat malesuada sed. Duis a placerat quam, eu vehicula est. </p>
        <p> Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque in lectus eget lacus semper feugiat. Pellentesque in lacus erat. Sed sem turpis, blandit quis vestibulum dapibus, viverra vitae diam. Curabitur non iaculis nibh, at bibendum turpis. Pellentesque aliquam faucibus sapien, imperdiet blandit tortor placerat at. Donec malesuada convallis nisi non sagittis. Donec tortor purus, egestas id tincidunt id, vestibulum vitae lorem. Maecenas sagittis posuere sem vitae consequat. Proin elit sem, semper non sodales pulvinar, ultrices cursus tellus. </p>
        <p> Duis euismod lorem in posuere aliquam. Maecenas eu pharetra sapien, a porta augue. Phasellus quis eros quam. Aliquam ac diam a mauris vulputate auctor. Donec at aliquam tellus. Ut euismod quam id dui venenatis, quis consequat libero accumsan. Cras porttitor quam porttitor magna lacinia consectetur. Ut maximus vitae est in tincidunt. Mauris vitae consectetur tellus, quis pellentesque orci. Vivamus sed orci ac tortor accumsan semper. Proin elementum nunc ac nibh venenatis, id ornare nisl accumsan. Quisque hendrerit consectetur turpis, non dignissim lacus. </p>
        <p> Fusce non aliquam sem, vitae maximus velit. Donec orci nulla, faucibus vitae commodo ac, porttitor lacinia mauris. Aliquam consectetur, libero quis tristique gravida, orci ante condimentum mauris, non ullamcorper massa magna sed quam. Phasellus rhoncus justo id augue vestibulum, eu consectetur neque venenatis. Mauris aliquet, magna non consequat laoreet, risus mauris dictum orci, a vestibulum tortor tortor nec est. Nunc tempus suscipit sapien, non pharetra sem convallis id. In hac habitasse platea dictumst. In in congue purus, ut cursus turpis. Quisque dapibus et ex vitae hendrerit. Donec placerat egestas ligula nec posuere. Aenean ut ex imperdiet nibh finibus congue. Pellentesque sed volutpat purus. Fusce egestas enim eleifend massa ornare tincidunt. Mauris placerat luctus magna ut luctus. </p>
        <p> Donec semper, lacus ac convallis sodales, metus purus convallis arcu, sit amet finibus ligula elit vel urna. Nunc sit amet nisl at turpis sodales vestibulum sed in nisi. Sed nisl ligula, commodo at eleifend in, hendrerit in lacus. Integer et felis ut nisi imperdiet maximus. Vestibulum purus erat, pharetra nec augue id, volutpat posuere quam. In hac habitasse platea dictumst. Nulla blandit hendrerit sem vitae malesuada. </p>
      </b-card>
    </b-col>
  </b-row>
</template>
