export default {
  assetCode: require('./assetCode').default,
  birthday: require('./birthday').default,
  birthPlace: require('./birthPlace').default,
  city: require('./city').default,
  companyName: require('./companyName').default,
  domain: require('./domain').default,
  email: require('./email').default,
  forename: require('./forename').default,
  lastname: require('./lastname').default,
  federationAddress: require('./federationAddress').default,
  mnemonic: require('./mnemonic').default,
  mobilePhone: require('./mobilePhone').default,
  password: require('./password').default,
  publicKey: require('./publicKey').default,
  state: require('./state').default,
  streetAddress: require('./streetAddress').default,
  streetNumber: require('./streetNumber').default,
  title: require('./title').default,
  twoFactorCode: require('./twoFactorCode').default,
  zipCode: require('./zipCode').default,
};
